export const DEFAULT_PARAMETERS = {
  INVENTORY_FORMAT: '{prefix}-{year}-{counter}',
  INVENTORY_PREFIX_DEFAULT: 'MAT',
  INVENTORY_COUNTER_PADDING: '4',
  INVENTORY_COUNTER_MODE: 'ANNUEL',
  QR_CODE_STRATEGY: 'INVENTORY_NUMBER',
  QR_CODE_BASE_URL: 'http://localhost:5173/materiels',
  LABEL_DEFAULT_FORMAT: 'SMALL',
  LABEL_DEFAULT_CONTENT: 'BOTH'
};
